App: #应用信息
  Name: jimoos-api-tracer
  Author:
  Description: 接口请求跟踪
  Addons:
    - Name: jm-utils
      Ref: jimoos-public
      Group: base
      SourceType: git
      Source:
      Description: 基础设置
      Type: module