spring:
  application:
    name: migration
---
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jimoos?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 5
    minIdle: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      exclude: static/**,templates/**
    livereload:
      enabled: true
    remote:
      debug:
        enabled: true
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 打开控制台debug颜色
  output:
    ansi:
      enabled: always
server:
  port: 9090
logging:
  level:
    root: warn
