spring:
  application:
    name: jimoos-api-tracer-portal
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jimoos?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 5
    minIdle: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      exclude: static/**,templates/**
    livereload:
      enabled: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  output:
    ansi:
      enabled: always
mybatis:
  # classpath* 此處的* 必須添加 否则会只扫描一个 jar 包，非常重要，2个小时的调试结果。
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: cn.jimoos.model
server:
  port: 4000
logging:
  level:
    root: info
